name: CI
on: [push, pull_request]
jobs:
  prebuilt_llvms:
    name: Test with prebuilt LLVM ${{ matrix.llvm }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - llvm: "13.0.0"
            ubuntu: 20
          - llvm: "12.0.0"
            ubuntu: 20
          - llvm: "11.0.0"
            ubuntu: 20
          - llvm: "10.0.0"
            ubuntu: 18
          - llvm: "9.0.0"
            ubuntu: 18
          - llvm: "8.0.0"
            ubuntu: 18
          - llvm: "7.0.1"
            ubuntu: 18
          - llvm: "6.0.1"
            ubuntu: 18
          - llvm: "5.0.2"
            ubuntu: 16
          - llvm: "4.0.0"
            ubuntu: 16
          - llvm: "3.9.1"
            ubuntu: 16
          - llvm: "3.8.1"
            ubuntu: 16
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Nidhugg
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: ci/Dockerfile.test${{ matrix.ubuntu }}
          build-args: LLVM_VERSION=${{ matrix.llvm }}
      - name: Run tests
        run: docker run --rm -t ${{ steps.build.outputs.digest }}
